# Generated by Django 3.2 on 2021-05-03 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_relationship_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='relationship',
            managers=[
            ],
        ),
    ]
