<<<<<<< HEAD
# Generated by Django 3.2 on 2021-05-04 12:01
=======
# Generated by Django 3.2 on 2021-05-04 13:18
>>>>>>> 69ce8a5375f9fe2068e43988a3366eff7a9eb9eb

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_relationship_managers'),
        ('groups', '0002_rename_user_group_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='groups', to='profiles.Profile'),
        ),
    ]
