# Generated by Django 3.2 on 2021-05-04 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_customprofanity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customprofanity',
            options={'verbose_name': 'Custom Profanity Word'},
        ),
    ]
