# Generated by Django 3.2 on 2021-05-05 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_notifications'),
        ('posts', '0006_alter_customprofanity_options'),
    ]

    operations = [
    ]
